[build.environment]
  NPM_VERSION = "6.13.4"
  TZ = "America/Los_Angeles"

[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build:preview"

[dev]
  command = "npm run start"
  targetPort = 8888
  TZ = "America/Los_Angeles"

[[redirects]]
  from = "/survey"
  to = "https://survey.alchemer.com/s3/6807408/EL-Drowning-in-Cairo"